jasontaylordev/CleanArchitecture

CleanArchitecture.sln
tests/Application.UnitTests/Application.UnitTests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj
tests/Infrastructure.IntegrationTests/Infrastructure.IntegrationTests.csproj

Had to fix capitalization of src directory in order to be able to build on Linux.
```
grep -rl --include *.sln --include *.csproj "Src" . |xargs sed -i 's/Src/src/g'
```

fix path \Src->\src

---

src/WebUI/Properties/launchSettings.json

https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1#generic-host

Update environment variables to .NET Core 3

---

src/WebUI/Program.cs

https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1#generic-host

Update to NET Core 3 Generic Host

---

src/Application/Common/Interfaces/IIdentityService.cs
src/Infrastructure/Identity/IdentityService.cs
tests/WebUI.IntegrationTests/TestIdentityService.cs

Found insignificant mistake in namespaces

Namespace and folder hierarchy mismatch fixed

---

README.md

Node Js link, explain that the template will use current directory as a project name and namespace

Add some steps to the Getting Started Section

---

README.md

Made version numbers of used technologies consistent across the README.md

Fixed inconsistent version numbers in README.md

---

src/Application/Common/Behaviours/ValidationBehavior.cs

Updated validation pipeline to execute async validations asynchronously

---

tests/Applicaton.IntegrationTests/Testing.cs

Fixes #147 
Thanks a lot @jasontaylordev for the recent improvements to testing.
I think it's much better now!

Throw on user creation failure and make find user more generic

---

src/Application/Common/Exceptions/ValidationException.cs
tests/Application.UnitTests/Common/Exceptions/ValidationExceptionTests.cs

1. Add unit tests for ValidationException constructor
2. Refactor the ValidationException constructor

Minor refactoring of the ValidationException constructor

---

.gitignore

1. Added rider cache/options directory to gitignore.

Added rider cache/options directory to gitignore

---

src/WebUI/Startup.cs

Fixes https://github.com/jasontaylordev/CleanArchitecture/issues/250

Used generic Add method to register filter.

---

.github/workflows/dotnetcore.yml
src/WebUI/ClientApp/package-lock.json
src/WebUI/ClientApp/package.json

I added a test stage to the workflow using a sql container

Add tests to CI

---

src/Application/TodoItems/EventHandlers/TodoItemCreatedEventHandler.cs

Fixed logger category name in TodoItemCreatedEventHandler

Fix logger category name

---

src/Application/TodoItems/Queries/GetTodoItemsWithPagination/GetTodoItemsWithPaginationQueryValidator.cs

NotEmpty already checks for null

Remove duplicate validator

---

tests/Application.IntegrationTests/TodoItems/Commands/DeleteTodoItemTests.cs

FindAsync shoud look for TodoItem with itemId, not listId

Change parameter variable

---

.gitignore
src/WebUI/ClientApp/src/app/app-routing.module.ts
src/WebUI/ClientApp/src/app/app.module.ts
src/WebUI/ClientApp/src/app/nav-menu/nav-menu.component.html
src/WebUI/ClientApp/src/app/token/token.component.html
src/WebUI/ClientApp/src/app/token/token.component.ts

This pull request adds a JWT viewer to the Angular app. This can be copied to the clipboard which can be useful for development (e.g. you can use the token in the Swagger UI page or in Postman).

Added token viewer component

---

README.md

Added video link to learn more about the template

README - add YouTube video to learn more about the template

---

tests/Application.IntegrationTests/Application.IntegrationTests.csproj
tests/Application.IntegrationTests/TodoItems/Commands/CreateTodoItemTests.cs
tests/Application.IntegrationTests/TodoItems/Commands/DeleteTodoItemTests.cs
tests/Application.IntegrationTests/TodoItems/Commands/UpdateTodoItemDetailTests.cs
tests/Application.IntegrationTests/TodoItems/Commands/UpdateTodoItemTests.cs
tests/Application.IntegrationTests/TodoLists/Commands/CreateTodoListTests.cs
tests/Application.IntegrationTests/TodoLists/Commands/DeleteTodoListTests.cs
tests/Application.IntegrationTests/TodoLists/Commands/PurgeTodoListsTests.cs
tests/Application.IntegrationTests/TodoLists/Commands/UpdateTodoListTests.cs
tests/Application.UnitTests/Application.UnitTests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj

hi 
I update FluentAssertions to version 6 
#430

update FluentAssertions to version 6

---

.gitignore
src/WebUI/ClientApp/src/app/app-routing.module.ts
src/WebUI/ClientApp/src/app/nav-menu/dev-env.guard.ts
src/WebUI/ClientApp/src/app/nav-menu/nav-menu.component.html
src/WebUI/ClientApp/src/app/nav-menu/nav-menu.component.ts

This pull request adds a condition to only show the JWT page in the menu in non-production environments. Also disables the route to the page if in production.

Added dev env conditions for token in angular app

---

src/WebUI/WebUI.csproj

https://github.com/jasontaylordev/CleanArchitecture/issues/528

fix --prod deprecated

---

README.md

Hi @jasontaylordev,
This PR updates Angular and ASP.NET Core versions on the README file to the current template versions, version 12 and 6 respectively.

Update Angular and ASP.NET Core version on readme to current template version

---

src/Application/TodoItems/Commands/CreateTodoItem/CreateTodoItemCommand.cs
src/Application/TodoItems/Commands/DeleteTodoItem/DeleteTodoItemCommand.cs
src/Application/TodoItems/Commands/UpdateTodoItem/UpdateTodoItemCommand.cs
src/Application/TodoItems/Commands/UpdateTodoItemDetail/UpdateTodoItemDetailCommand.cs
src/Application/TodoItems/Queries/GetTodoItemsWithPagination/GetTodoItemsWithPaginationQuery.cs
src/Application/TodoLists/Commands/CreateTodoList/CreateTodoListCommand.cs
src/Application/TodoLists/Commands/DeleteTodoList/DeleteTodoListCommand.cs
src/Application/TodoLists/Commands/PurgeTodoLists/PurgeTodoListsCommand.cs
src/Application/TodoLists/Commands/UpdateTodoList/UpdateTodoListCommand.cs
src/Application/TodoLists/Queries/ExportTodos/ExportTodosQuery.cs
src/Application/TodoLists/Queries/GetTodos/GetTodosQuery.cs
src/Application/WeatherForecasts/Queries/GetWeatherForecasts/GetWeatherForecastsQuery.cs
src/WebUI/Controllers/TodoItemsController.cs
src/WebUI/Controllers/TodoListsController.cs
tests/Application.IntegrationTests/TodoItems/Commands/DeleteTodoItemTests.cs
tests/Application.IntegrationTests/TodoLists/Commands/DeleteTodoListTests.cs

Based on the PR #348 on issues #347 and the discussion in #314
This PR only applies to the commands and queries and does not change anything else.
If a command/query has a single argument then it has a constructor, otherwise it has a list of properties with get; init;

Command & Queries to use records

---

.github/workflows/dotnet.yml
src/WebUI/WebUI.csproj

- 💚 Update dotnet workflow to remove dotnet-ef install (not required)
- 🐛 Remove deprecated flag for ng build
- 🚀 Add deploy to staging job
- 🚀 Add deploy to prod job

Deploy to Azure

---

src/Domain/ValueObjects/Colour.cs

Errant string in Colour value object

Fix colour typo

---

src/WebUI/WebUI.csproj

Removed secrets ID from WebUI project

---

src/WebUI/Program.cs
src/WebUI/WebUI.csproj
tests/Application.IntegrationTests/CustomWebApplicationFactory.cs

Adjust scope of WebUI.Program #679
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#basic-tests-with-the-default-webapplicationfactory

IntegrationTests - Expose internals of WebUI through InternalsVisibleTo

---

src/WebUI/ClientApp/src/app/nav-menu/nav-menu.component.html

Added Todo, JWT, and API links back to the nav menu

---

global.json
src/WebUI/WebUI.csproj

📦 Update global.json
🧑‍💻 Auto-generation of Open API spec and Angular clients.

Upgrade7.0

---

.github/workflows/codeql-analysis.yml

Upgrade CodeQL

---

src/Domain/Entities/TodoItem.cs

We can remove boolean literals from expressions to improve readability

Added Changes to improve readability for Boolean literals

---

CleanArchitecture.sln
playground/TodoItems.http
playground/TodoLists.http
playground/WeatherForecast.http

Added playground to execute http request internaly with Visual Studio 2022 17.5 release 
https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-5-released/#api

Added http calls API development inner-loop Visual Studio 2022 17.5

---

templates/ca-use-case/FeatureName/Queries/CleanArchitectureUseCase/CleanArchitectureUseCase.cs

Generate Correct Query Validator instead of generating the wrong one

Update Validator in Query  Template

---

templates/ca-use-case/FeatureName/Queries/CleanArchitectureUseCase/CleanArchitectureUseCase.cs

fix wrong generated constructor for query validator

fix wrong generated constructor for query validator

---

src/Application/TodoLists/Commands/PurgeTodoLists/PurgeTodoLists.cs
src/Domain/Constants/Policies.cs
src/Domain/Constants/Roles.cs
src/Infrastructure/ConfigureServices.cs
src/Infrastructure/Data/ApplicationDbContextInitialiser.cs
tests/Application.IntegrationTests/Testing.cs

Centralize roles and policies magic strings, I create separate classes in a folder/namespace to have better modularity.

Centralize role and policy constants into Domain

---

.template.config/template.json
CleanArchitecture.nuspec
CleanArchitecture.sln
README-template.md
README.md

This README will be included for solutions created using the template.
It details building, running, testing, code scaffolding, and help.

🧑‍💻Added README for templated solutions

---

src/Web/ClientApp-React/README.md

🐛 Fix typo in ClientApp-React/README.md

---

Directory.Packages.props

Updated Azure.Identity to 1.10.3 in order to fix https://github.com/advisories/GHSA-5mfx-4wcx-rv27

Updated Azure.Identity to 1.10.3

---

.template.config/template.json
CleanArchitecture.nuspec
README-template.md

Fixed React template issue - missing NSwag templates required for the build.

🐛 Fixes #1057

---

.template.config/template.json
CleanArchitecture.nuspec
Directory.Packages.props
README-template.md
global.json
src/Web/ClientApp/src/app/web-api-client.ts
src/Web/DependencyInjection.cs
src/Web/Program.cs
src/Web/wwwroot/api/specification.json

📦 Upgrade NSwag and other packages

---

README.md

Updated command for installing project template for .NET 6.

Updated CLI command

---

src/Domain/ValueObjects/Colour.cs

Introduced primary constructor concept

refactor(PrimaryConstructor):

---

Directory.Build.props

Simplified Output Paths enabled  on .net8 #938

enable: Simplified Output Paths on .net8 #938

---

.template.config/template.json
CleanArchitecture.nuspec
README.md
src/Web/wwwroot/api/specification.json

Add missing Identity endpoints to Open API specification.

Fix Open API Specification

---

.scripts/setup.ps1

when a user has multiple subscriptions, make sure the correct one is used.

Make sure the correct subscription is used.

---

.github/workflows/azure-dev.yml
.github/workflows/codeql.yml

- Update CodeQL version
- Update .NET version

📦 Upgrade Workflows

---

src/Application/Common/Mappings/MappingExtensions.cs
src/Application/Common/Models/PaginatedList.cs
src/Application/TodoItems/Queries/GetTodoItemsWithPagination/GetTodoItemsWithPagination.cs

Issue Link: https://github.com/jasontaylordev/CleanArchitecture/issues/1296

chore: pass cancellation token in paginatedlistasync

---

.editorconfig

fix for #1213

---

.github/workflows/package.yml

This pull request updates the `.github/workflows/package.yml` file to modernize the CI workflow by upgrading dependencies and adding a new step for Mono installation.

🐛 Fix package workflow

---

.github/workflows/package.yml

This pull request introduces a minor update to the GitHub Actions workflow configuration. It adds the ability to manually trigger the workflow using the `workflow_dispatch` event in the `.github/workflows/package.yml` file.

👷 Run on demand

---

.azdo/pipelines/azure-dev.yml
.github/workflows/azure-dev.yml
.template.config/template.json
CleanArchitecture.nuspec
README.md

This pull request updates Azure DevOps and GitHub Actions pipeline configurations to improve compatibility and streamline setup processes. Key changes include upgrading task versions, adding new configurations for session management, and simplifying Azure authentication in GitHub workflows.

Upgrade pipelines

---

src/Application/Common/Behaviours/AuthorizationBehaviour.cs
src/Application/Common/Interfaces/IUser.cs
src/Web/Services/CurrentUser.cs
src/Web/Web.csproj
tests/Application.FunctionalTests/CustomWebApplicationFactory.cs
tests/Application.FunctionalTests/Testing.cs

Implement proposal Improve authorization performance #1046
Moved Roles authorization from Identity Service DB verification to verify Roles user Claim.

Implement proposal Improve authorization performance

---

Directory.Packages.props
src/Application/Application.csproj
src/Domain/Domain.csproj

Replaced MediatR with MediatR.Contracts in the Domain project to avoid bringing in unnecessary dependencies. Added full MediatR package to the Application project, where request handling occurs.

Refactor MediatR package references
