src/Application/Application.csproj
src/Infrastructure/Infrastructure.csproj
src/WebUI/WebUI.csproj
tests/Application.UnitTests/Application.UnitTests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj
tests/Infrastructure.IntegrationTests/Infrastructure.IntegrationTests.csproj
tests/WebUI.IntegrationTests/WebUI.IntegrationTests.csproj

Update TargetFramework 3.0 to 3.1 (Infrastructure, WebUI, Test projects)
Updated Application project NuGet packages
-     FluentValidation 8.5.0->8.6.0
-     Microsoft.EntityFrameworkCore 3.0.0->3.1.0
Updated Infrastructure project NuGet packages
-     CsvHelper 12.1.2->12.2.2
-     Microsoft.AspNetCore.ApiAuthorization.IdentityServer 3.0.0->3.1.0
-     Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.0.0->3.1.0
-     Microsoft.EntityFrameworkCore.SqlServer 3.0.0->3.1.0
Updated WebUI project NuGet packages
-     FluentValidation.AspNetCore 8.5.0->8.6.0
-     NSwag.AspNetCore 13.1.2->13.1.6
-     NSwag.MSBuild 13.1.2->13.1.6
-     Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.0.0->3.1.0
-     Microsoft.AspNetCore.SpaServices.Extensions 3.0.0->3.1.0
- …

Update to .NET Core 3.1 LTS

---

src/Application/Common/Exceptions/ValidationException.cs

This reduces the iterations in the constructor of ValidationException to the necessary minimum.

Small improvement to ValidationException ctor.

---

src/Application/Common/Exceptions/ValidationException.cs

I've changed List to IEnumerable according to ["**Parameter Design**"](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/parameter-design) section of "**Microsoft Design Guidelines**":
> ✔ **DO** use the least derived parameter type that provides the functionality required by the member.
> 
> For example, suppose you want to design a method that enumerates a collection and prints each item to the console. Such a method should take IEnumerable as the parameter, not ArrayList or IList, for example.

Using more general type (IEnumerable) as input parameter

---

README.md

Add details on flags needed to run database migrations as it can be fairly confusing for people coming from a traditional single project world. (or perhaps one in which your migrations are within your web project.)
In relation to issue #33
This readme change is likely out of scope. If you feel this way please reject this PR outright. Thank you!

add database migrations to readme

---

src/Application/Common/Behaviours/ValidationBehaviour.cs
src/Application/DependencyInjection.cs

Renamed class to match non-american version of the word behavior for consistency.

Rename ValidationBehavior to ValidationBehaviour

---

src/Domain/Entities/TodoList.cs

Implement the change made during the GOTO 2019 talk here:
https://youtu.be/dK4Yb6-LxAk?t=800
Private setters on collections prevent collection overriding.

Private setter on collections in domain entity

---

src/WebUI/nswag.json

This fixes an issue (#176) with resolving the Angular client after initializing the template on a Linux machine (which has case-sensitivity for filepaths).

Made NSwag output filename lowercase

---

src/WebUI/Services/CurrentUserService.cs
src/WebUI/Startup.cs

Since `HttpContext` is using `AsyncLocal` internal while the `CurrentUserService` is using DI (scope), there might be cases where there is a synchronisation issue that causes the wrong or `null` UserId to be returned.  Is it safe to have a Singleton service which retrieves the current context from the accessor as suggested by David Fowler - https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field

Changed HttpContextAccessor to retrieve context when getter is called

---

src/Domain/Entities/TodoList.cs

It's better to initialize the collection in the declaration so that if more constructors were added, there would be no need to initialize the collection in every constructor.

Remove constructor and use collection initializer

---

src/Application/Common/Interfaces/IDomainEventService.cs
src/Application/Common/Models/DomainEventNotification.cs
src/Application/TodoItems/Commands/CreateTodoItem/CreateTodoItemCommand.cs
src/Application/TodoItems/EventHandlers/TodoItemCompletedEventHandler.cs
src/Application/TodoItems/EventHandlers/TodoItemCreatedEventHandler.cs
src/Domain/Common/AuditableEntity.cs
src/Domain/Common/DomainEvent.cs
src/Domain/Domain.csproj
src/Domain/Entities/TodoItem.cs
src/Domain/Events/TodoItemCompletedEvent.cs
src/Domain/Events/TodoItemCreatedEvent.cs
src/Infrastructure/DependencyInjection.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs
src/Infrastructure/Persistence/Configurations/TodoItemConfiguration.cs
src/Infrastructure/Persistence/Configurations/TodoListConfiguration.cs
src/Infrastructure/Services/DomainEventService.cs

This PR adds Domain Events to the solution template.  Domain events implement side effects of changes across multiple aggregates, entities or services and provide very loose coupling.  Let's look at an example:
When a user places an order with an online store an email is sent back to the user confirming the purchase.  This could be done in a workflow in a single command where the data is saved to the database and then an email is sent.  Or you can handle the order placed as a command that throws an order placed event.  Then a separate event handler can send the email.  If in the future a new action is identified such as also sending an email to the fulfillment center, it can be added without changing the previous command.
There are two separate ways to fire domain events.
1. **During Save …

[Feature] Domain Events

---

src/Domain/Common/DomainEvent.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs

In case there's a domain event handler that's also triggering another domain event, it will enter an infinite loop.
To fix this, I am checking if the domain event has already been fired after its initialization.

Fix DispatchEvents() that caused an infinite loop of events

---

src/Domain/Enums/PriorityLevel.cs

It is very common to discover that you need to add values to an enum after you have already shipped it. There is a potential application compatibility problem when the newly added value is returned from an existing API, because poorly written applications might not handle the new value correctly.

Provide enum values

---

tests/Application.UnitTests/Common/Mappings/MappingTests.cs

It is oftentimes the case, that You don't allow entities with parameterless constructor in Your project to prevent developers for creating invalid entities. I found mapping test very elegant and I see a benefit for other developers, which might wanna use them in their projects.
GetUninitialized method creates an instance of an object and set all fields to default value, but do not call any of constructors. So mapping tests are still valid, but we skip any constructor-related issues if we cannot or don't have access to parameterless constructor

Mapping test should handle entities without parameterless constructor

---

src/Domain/Common/ValueObject.cs
src/Domain/ValueObjects/AdAccount.cs

Hi there!
The `ValueObject` implementation in eShopOnContainers was recently updated according to this PR: https://github.com/dotnet-architecture/eShopOnContainers/pull/1316.
This new implementation cuts down on some of the complex code by using `SequenceEqual()` & the method name was changed to make the intent clearer. The docs page linked to at the top of `ValueObject` has also been updated here: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#value-object-implementation-in-c
This PR just updates the implementation of `ValueObject` & updates the one method call to `GetEqualityComponents()`

refactor(value object)

---

src/WebUI/WebUI.csproj
src/WebUI/nswag.json

The MSBuild  configurations for NSwagg command line was still trying to use Net core 3.1 runtime.
It was causing my builds to fail. The fix was to change the  $NSwagExe_31 variable  to $NSwagExe_50 to 
For more information you can visit [NSwag.MSBuild](https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild) 🙂

.Net 5 Fixed Build issue caused by  Nswag MSBuild  runtime variable configuration 

---

src/WebUI/ClientApp/src/app/app-routing.module.ts
src/WebUI/ClientApp/src/app/app.module.ts

Hello,
this is my first public pull request so forgive me if I get something wrong.
I moved the routing paths from the app.module file into a separate app-routing.module.ts file as that is likely what every developer will do once the app has more than a couple routes.  Its also best practice according to[ angular.io. ](https://angular.io/guide/router) 
One final benefit is if you try to add something like nativescript, it can better discover the existing routes when creating the new nativescript code sharing project.
This is a preference change and does not change app functionality so integrate it if you like
Cheers

use routing module for main app module

---

src/Infrastructure/Persistence/ApplicationDbContext.cs

In order to avoid the exception: "The DbContextOptions passed to the ApplicationDbContext constructor must be a DbContextOptions<ApplicationDbContext>. When registering multiple DbContext types, make sure that the constructor for each context type has a DbContextOptions<TContext> parameter rather than a non-generic DbContextOptions parameter."

Add <ApplicationDbContext> to DbContextOptions parameter on ApplicationDbContext constructor

---

src/Application/Common/Models/PaginatedList.cs

Hi @jasontaylordev !
This simple PR replaces the variable name from "PageIndex" to "PageNumber" as it should start from 1, not 0. Also in GetTodoItemsWithPaginationQuery.cs class, it creates pageNumber and passes to PaginatedList.cs.

Changed 'pageIndex' variable name to 'pageNumber' in PaginatedList.cs

---

src/Application/TodoItems/Commands/DeleteTodoItem/DeleteTodoItemCommand.cs
src/Domain/Events/TodoItemDeletedEvent.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs

Suppose you want an event to be published at the same time when a "TodoItem" is deleted ex:
> ...
> entity.DomainEvents.Add(new TodoItemDeletedEvent(entity));
> ...
**This event will not be published!**
This is because "ChangeTracker" in "EFCore" after calling
> var result = await base.SaveChangesAsync(cancellationToken);
Removes all deleted changes from the "ChangeTracker" history, leaving event output empty.
That's why we need to save the events before clearing "ChangeTracker" so that we can publish the events after applying the changes to the database.
So we will have:
```
var events = ChangeTracker.Entries<IHasDomainEvent>()
.Select(x => x.Entity.DomainEvents)
.SelectMany(x => x)
.Where(domainEvent => !domainEvent.IsPublished)
.ToArray();
var result = await …
```

Solve the problem of publishing deleted events

---

.github/workflows/dotnetcore.yml
global.json

Control the .net version using the global.json file - that way the github action runners will always grab the right version

🏗️ control .net version through global.json

---

src/WebUI/Dockerfile

The .NET projects were migrated to .NET 6.0 but the Dockerfile remained in the 5.0 version

fix(Dockerfile): update to NET 6.0

---

src/Application/Common/Mappings/MappingExtensions.cs

As it is used CQRS pattern for the better performance in read model we could use no-tracking query by default in PaginatedListAsync and ProjectToListAsync methods in mapping extensions.

Added .AsNoTracking() for list projections

---

src/Application/Common/Behaviours/LoggingBehaviour.cs
src/Application/Common/Interfaces/IIdentityService.cs
src/Infrastructure/Identity/IdentityService.cs
src/Infrastructure/Persistence/ApplicationDbContextInitialiser.cs

Simple fix, but ideally would be great if we could enforce somehow that `IdentityRole.Name` is nullable.  Might be able to do this by implementing our own `RoleStore`, but that seems overkill.

Fixed warnings caused by IdentityRole.Name being nullable

---

src/WebUI/ConfigureServices.cs

ICurrentUser was changed to Singleton by PR #168  
But the current user service shouldn't share a single instance in the whole application. With the current behavior being singleton, the UserId is not always guaranteed  to be the one of the current user. 
As an example, inject ICurrentUser in a method that has heavy computation. You get the UserId at the start of the method and start the execution of the heavy task. In the same time , the web server is accessed by another user and the CurrentUserId is then changed to the second user's ID. 
We go back to the long running task for User 1. By the end of it, we check again the currentUserService UserId. This time the Id is the one of the User 2, so we get inconsistent behavior. 
---
The integration tests at the moment are not accounting for …

Change the ICurrentUserService to Scoped

---

src/Application/Application.csproj
src/Application/Common/Behaviours/AuthorizationBehaviour.cs
src/Application/Common/Behaviours/PerformanceBehaviour.cs
src/Application/Common/Behaviours/UnhandledExceptionBehaviour.cs
src/Application/Common/Behaviours/ValidationBehaviour.cs
src/Domain/Domain.csproj
src/Infrastructure/Files/CsvFileBuilder.cs
src/Infrastructure/Files/Maps/TodoItemRecordMap.cs
src/Infrastructure/Infrastructure.csproj
src/WebUI/WebUI.csproj
tests/Application.IntegrationTests/Application.IntegrationTests.csproj
tests/Application.IntegrationTests/Testing.cs
tests/Application.UnitTests/Application.UnitTests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj

Upgrade dotnet from rc2 to 7
Upgrade ef from rc2 to 7
Upgrade other library and fix breaking changes
List of upgradated library
Application.csproj
FluentValidation.DependencyInjectionExtensions from 10.3.4 to 11.4.0
MediatR.Extensions.Microsoft.DependencyInjection from 9.0.0 to 11.0.0
Microsoft.EntityFrameworkCore 7.0.0-rc.2.22472.11  to 7.0.2
Domain.csproj
MediatR from 9.0.0 to 11.1.0
Infrastructure.csproj
CsvHelper from 15.0.10 to 
Microsoft.AspNetCore.ApiAuthorization.IdentityServer from 7.0.0-rc.2.22476.2 to 30.0.1
Microsoft.AspNetCore.Identity.EntityFrameworkCore from 7.0.0-rc.2.22476.2 to 7.0.2
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore from 7.0.0-rc.2.22476.2 to 7.0.2
Microsoft.EntityFrameworkCore.SqlServer from 7.0.0-rc.2.22472.11 to 7.0.2 …

Upgrade dotnet from rc2 to 7

---

src/Application/Common/Models/LookupDto.cs
src/Application/Common/Models/PaginatedList.cs
src/Application/Common/Models/Result.cs
src/Application/TodoItems/Queries/GetTodoItemsWithPagination/TodoItemBriefDto.cs
src/Application/TodoLists/Queries/ExportTodos/ExportTodosVm.cs
src/Application/TodoLists/Queries/ExportTodos/TodoItemFileRecord.cs
src/Application/TodoLists/Queries/GetTodos/PriorityLevelDto.cs
src/Application/TodoLists/Queries/GetTodos/TodoItemDto.cs
src/Application/TodoLists/Queries/GetTodos/TodoListDto.cs
src/Application/TodoLists/Queries/GetTodos/TodosVm.cs
src/Application/WeatherForecasts/Queries/GetWeatherForecasts/WeatherForecast.cs

Immutable objects are safe to use.
Example:
```
void Foo(Dto dto)
{
var res1 = service1.Bar(dto);
var res2 = service2.Bar(dto);
...
Some logic with res1
...
Some logic with res2
...
}
```
If dto is immutable, one can safely remove or change the call to `service1` and be sure, that logic related to `res2` is not affected. But if dto is muttable, we have to investigate all possible call chains on service1 in order to make the refactoring, because I don't know in advance how dto is mutated during the call to `service1`.
The good practice is not to mutate objects which are passed as arguments to public methods. This makes maintenance much easier.
Currently, Dtos (under `src/Application`) are not immutable because they contain public setters fields of mutable types like IList
Let's replace set …

Make Dtos immutable

---

src/Application/Application.csproj
src/Application/Common/Behaviours/AuthorizationBehaviour.cs
src/Application/Common/Behaviours/PerformanceBehaviour.cs
src/Application/Common/Behaviours/UnhandledExceptionBehaviour.cs
src/Application/Common/Behaviours/ValidationBehaviour.cs
src/Application/ConfigureServices.cs
src/Application/TodoItems/Commands/DeleteTodoItem/DeleteTodoItemCommand.cs
src/Application/TodoItems/Commands/UpdateTodoItem/UpdateTodoItemCommand.cs
src/Application/TodoItems/Commands/UpdateTodoItemDetail/UpdateTodoItemDetailCommand.cs
src/Application/TodoLists/Commands/DeleteTodoList/DeleteTodoListCommand.cs
src/Application/TodoLists/Commands/PurgeTodoLists/PurgeTodoListsCommand.cs
src/Application/TodoLists/Commands/UpdateTodoList/UpdateTodoListCommand.cs
src/Application/WeatherForecasts/Queries/GetWeatherForecasts/GetWeatherForecastsQuery.cs
src/Domain/Domain.csproj
src/Infrastructure/Infrastructure.csproj
src/WebUI/WebUI.csproj
tests/Application.IntegrationTests/Application.IntegrationTests.csproj
tests/Application.IntegrationTests/Testing.cs
tests/Application.UnitTests/Application.UnitTests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj

Upgrade .net from 7.0.2 to 7.0.3
Upgrade FluentValidation from 11.0.4 to 11.5.1
Upgrade MediatR from 11.1.0 to 12.0.0
Upgrade EntityFramework from 7.0.2 to 7.0.3
Upgrade FluentAssertions from 6.9.0 to 6.10.0

Library Upgrade and Mediatr 12 fix

---

CleanArchitecture.nuspec

Fix, error handling, and input maxLength.
Closes #788 @jasontaylordev This is the new PR against the main branch. I closed the previous one.

Fix, error handling and input maxLength

---

src/Domain/Common/BaseEntity.cs

Rather than support generic key types as proposed in #826, I have included a comment to describe the reasoning behind BaseEntity.Id key type. This is inline with the approach taken in [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/ApplicationCore/Entities/BaseEntity.cs).

💡 Describe the reasoning behind BaseEntity.Id key type.

---

src/Web/Program.cs

I propose removing the migration endpoint. Currently, the migration endpoint is only added when the application is in the `IsDevelopment()` environment. However, we already have automatic database migration implemented through the `InitialiseDatabaseAsync()` → `InitialiseAsync()` → `MigrateAsync()` flow. As a result, the migration endpoint is redundant and can be safely removed.

🔥 Removed UseMigrationsEndPoint feature.

---

.scripts/setup.ps1

The function GenerateRandomPassword always return same output as the defined valid chars without applying any randomization.
// Testing done by executing the function in PowerShell
Input
```
GenerateRandomPassword
GenerateRandomPassword 5
```
Output (Bug)
```
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#^_-+=?<>|~
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#^_-+=?<>|~
```
Output after fix
```
Z230b>?muoy54aQW
3|VFC
```

Fix randomization bug in GenerateRandomPassword function.

---

.azure/bicep/main.bicep

This _appears_ to be a trivial oversight from July's change to this file. Cheers.

Fix description of allowed environment names in main bicep

---

src/Domain/Common/ValueObject.cs

[I recommend to use HashCode ](https://stackoverflow.com/a/51716512/2618513)
> Pros:
> 
> - Part of .NET itself, as of .NET Core 2.1/.NET Standard 2.1 (though, see con below)
>     - For .NET Framework 4.6.1 and later, the [Microsoft.Bcl.HashCode](https://www.nuget.org/packages/Microsoft.Bcl.HashCode) NuGet package can be used to backport this type.
> - Looks to have good performance and mixing characteristics, based on the work the author and the reviewers did before [merging this into the corefx repo](https://github.com/dotnet/coreclr/pull/14863)
> - Handles nulls automatically
> - Overloads that take [IEqualityComparer](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1?view=netcore-2.1) instances

chore: use System.HashCode struct to generate hash code instead of XOR values

---

src/Infrastructure/Data/Interceptors/AuditableEntityInterceptor.cs

Seems more correct to have the initial LastModifiedBy timestamp exactly equal the CreatedBy timestamp rather than being very slightly later with an additional call to _dateTime.GetUtcNow()

Use the Created DateTimeOffset for initial LastModified in MainAuditableEntityInterceptor.UpdateEntities

---

src/Infrastructure/Data/ApplicationDbContext.cs

Follow this [post](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2) and this [issue](https://github.com/dotnet/efcore/issues/9503#issuecomment-431318312)
This will fix issues related to custom TKey in Identity
> When overriding OnModelCreating, base.OnModelCreating should be called first; the overriding configuration should be called next. EF Core generally has a last-one-wins policy for configuration. For example, if the ToTable method for an entity type is called first with one table name and then again later with a different table name, the table name in the second call is used.
When trying to customize identity

Fix override OnModelCreating

---

tests/Application.UnitTests/Common/Mappings/MappingTests.cs

Replaces obsolete `System.Runtime.Serialization` `FormatterServices.GetUninitializedObject` reference in MappingTests with equivalent version in `System.Runtime.CompilerServices`.
Based on the workaround described here:
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0050#workaround

Replace System.Runtime.Serialization GetUninitializedObject method

---

.editorconfig

Makes indentation consistent across all IDEs when working with Javascript files.

Add missing .editorconfig settings for Javascript

---

src/Infrastructure/Identity/IdentityService.cs

Changing to FindByIdAsync means EF doesn't send the same database query over and over when querying the same user's information in the same request. For SQL UserStore at least: https://github.com/dotnet/aspnetcore/blob/5c17b92560953e86f1ea8502a567bcb3a1be4a2f/src/Identity/EntityFrameworkCore/src/UserStore.cs#L219
Improves #1046, see my comment there.

IdentityService.cs - use FindByIdAsync

---

src/Web/Infrastructure/IEndpointRouteBuilderExtensions.cs

This will highlight route string, and also enable some messages that might indicate if a route is invalid (it has route parameters that aren't defined in the method that's bound to it.

Added StringSyntax for http mapping

---

Directory.Packages.props

according to microsoft https://github.com/advisories/GHSA-m5vv-6r4h-3vj9 
Affected versions Azure.Identity
< 1.11.4

Update Directory.Packages.props to patch moderate severity vulnerability

---

src/Application/TodoLists/Commands/CreateTodoList/CreateTodoListCommandValidator.cs
src/Application/TodoLists/Commands/UpdateTodoList/UpdateTodoListCommandValidator.cs

- Replaced the `AllAsync` method with `AnyAsync` in the `BeUniqueTitle` method of `CreateTodoListCommandValidator`.
- This change improves performance by stopping the query as soon as the first matching title is found, rather than checking all records.
- The new implementation checks if any `TodoList` record has a matching title, which is more efficient, especially for large datasets.
- **Before**: 
```csharp
return await _context.TodoLists
.AllAsync(l => l.Title != title, cancellationToken);
```
- **After**: 
```csharp
return !await _context.TodoLists
.AnyAsync(l => l.Title == title, cancellationToken);
```
This optimization enhances performance when validating unique `Title` values.

Optimize improve performance by using AnyAsync

---

.github/workflows/codeql.yml

Added additional permissions for the analyze job so the action is able to checkout the code of it is a private repository. Otherwise a "repository <repository> not found" error is displayed.

Update codeql.yml to allow for private repositories to be checked-out.

---

src/Web/ClientApp-React/aspnetcore-https.js
src/Web/ClientApp/aspnetcore-https.js

Fixes the issue mentioned in #1266 and #1247. For reference:
> There has been a breaking change to the behaviour of dotnet dev-certs, it no longer creates a file path if its missing.
> 
> In the npm start https prerun script aspnetcore-https.js it runs the dev-certs command but errors if the file path does not exist due to the behaviour change. Needs to be updated to instead check if the dir exists and create it instead.
> 
> Can see the changes documented here - [link](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/9.0/certificate-export)

🐛 Automatically create the https folder.

---

.template.config/template.json
CleanArchitecture.nuspec
README.md
src/AppHost/Program.cs
src/Web/ClientApp-React/src/web-api-client.ts
src/Web/ClientApp/src/app/web-api-client.ts
src/Web/Infrastructure/WebApplicationExtensions.cs
src/Web/wwwroot/api/specification-webapi.json
src/Web/wwwroot/api/specification.json

🐛 Fix Open API spec / client generation
🧑‍💻 Tweak code for Sqlite option

General Updates V2

---

.template.config/template.json
CleanArchitecture.nuspec
README.md

🐛 Exclude jekyll-gh-pages workflow and funding configuration from template

---

src/Infrastructure/Data/ApplicationDbContextInitialiser.cs
src/Infrastructure/DependencyInjection.cs

This pull request refactors the database initialization and seeding logic to utilize the new `UseAsyncSeeding` method introduced in EF Core 9, improving the seeding process for the Clean Architecture project. The changes ensure better asynchronous handling during database setup and enhance maintainability.
**Changes:**
1. **New `AddAsyncSeeding` Method:**
- Introduced an extension method `AddAsyncSeeding` that configures the `DbContextOptionsBuilder` to use the new `UseAsyncSeeding` method.
- This method ensures that the seeding logic runs asynchronously, with service provider access to perform necessary operations like creating default roles and users.
2. **Refactored `ApplicationDbContextInitialiser`:**
- The seeding logic in `ApplicationDbContextInitialiser` was retained but refactored …

feat: Update Database Seeding Implementation for EF Core 9 Compatibility

---

src/Web/ClientApp-React/package.json
src/Web/ClientApp-React/src/components/Home.js
src/Web/ClientApp-React/src/components/SampleComponent.tsx
src/Web/ClientApp-React/tsconfig.json

Implementation of tsx support for react

Implementation of tsx support for react

---

src/Web/Endpoints/TodoItems.cs
src/Web/Endpoints/TodoLists.cs
src/Web/Endpoints/WeatherForecasts.cs
src/Web/Infrastructure/EndpointGroupBase.cs
src/Web/Infrastructure/IEndpointRouteBuilderExtensions.cs
src/Web/Infrastructure/WebApplicationExtensions.cs

Hi,  
I updated the endpoint mapping to use RouteGroupBuilder instead of WebApplication.  
This lets us organize routes better and apply settings more precisely—for example, requiring authorization on just one method instead of the whole group.  
I also added a way to name these groups more clearly instead of relying on class names.  
Please review when you get a chance and let me know if you have any feedback.  
Thanks!

Refactor endpoint mapping to use RouteGroupBuilder
